"""Vendor Cortex contract artifacts and regenerate ``cortex_client.generated``.

Copies from CORTEX_ROOT:
  - contract/openapi-1.1.0.json + .sha256
  - contract/testvectors/manifest_canonical.jsonl

Then prunes a generation surface and runs openapi-python-client into
``packages/cortex_client/cortex_client/generated/``.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC_NAME = "openapi-1.1.0.json"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sync_artifacts(cortex_root: Path) -> None:
    src_spec = cortex_root / "contract" / SPEC_NAME
    src_hash = cortex_root / "contract" / f"{SPEC_NAME}.sha256"
    src_vectors = cortex_root / "contract" / "testvectors" / "manifest_canonical.jsonl"
    for p in (src_spec, src_hash, src_vectors):
        if not p.is_file():
            raise SystemExit(f"missing Cortex artifact: {p}")

    dest = ROOT / "contract"
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "testvectors").mkdir(parents=True, exist_ok=True)
    shutil.copy2(src_spec, dest / SPEC_NAME)
    shutil.copy2(src_hash, dest / f"{SPEC_NAME}.sha256")
    shutil.copy2(src_vectors, dest / "testvectors" / "manifest_canonical.jsonl")

    expected = (dest / f"{SPEC_NAME}.sha256").read_text(encoding="utf-8").split()[0]
    actual = _sha256(dest / SPEC_NAME)
    if actual != expected:
        raise SystemExit(f"sha256 mismatch for {SPEC_NAME}: {actual} != {expected}")

    vec = dest / "testvectors" / "manifest_canonical.jsonl"
    (dest / "testvectors" / "manifest_canonical.jsonl.sha256").write_text(
        f"{_sha256(vec)}  manifest_canonical.jsonl\n", encoding="utf-8"
    )
    print(f"synced {SPEC_NAME} ({actual[:12]}…) + testvectors")


def regenerate_client() -> None:
    prune = ROOT / "scripts" / "prune_contract_openapi.py"
    subprocess.check_call([sys.executable, str(prune)], cwd=str(ROOT))
    gen_spec = ROOT / "contract" / "openapi-1.1.0.gen.json"
    tmp = ROOT / "_gen_cortex_client"
    if tmp.exists():
        shutil.rmtree(tmp)
    cmd = [
        sys.executable,
        "-m",
        "openapi_python_client",
        "generate",
        "--path",
        str(gen_spec),
        "--output-path",
        str(tmp),
        "--overwrite",
        "--meta",
        "none",
    ]
    subprocess.check_call(cmd, cwd=str(ROOT))
    dest = ROOT / "packages" / "cortex_client" / "cortex_client" / "generated"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.move(str(tmp), str(dest))
    (dest / "README.md").write_text(
        "# Auto-generated by scripts/sync_contract.py\n\nDo not hand-edit. Run: just sync-contract\n",
        encoding="utf-8",
    )
    # gen.json is a build intermediate — keep for local regen, gitignore optional
    print(f"regenerated {dest}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--cortex-root",
        type=Path,
        default=Path(os.environ.get("CORTEX_ROOT", r"D:\Cortex")),
    )
    p.add_argument("--skip-generate", action="store_true")
    args = p.parse_args()
    sync_artifacts(args.cortex_root)
    if not args.skip_generate:
        regenerate_client()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
